### ISSUE TITLE
Code from "master" falls.

### ISSUE THREAD

**Issue by isabsent** [yandex-disk/yandex-disk-restapi-java#1]
**Why am I getting error on 4.1.2 and 5.0 Android devices when run your example app:** 

11-09 12:42:45.963 10998-12181/com.yandex.disk.rest.example D/LoadFileFragment: loadFile
11-09 12:42:45.963 10998-12181/com.yandex.disk.rest.example D/LoadFileFragment: HttpCodeException{code=416, response=null}
11-09 12:42:45.963 10998-12181/com.yandex.disk.rest.example D/LoadFileFragment:     at com.yandex.disk.rest.RestClientIO.downloadUrl(RestClientIO.java:119)
11-09 12:42:45.963 10998-12181/com.yandex.disk.rest.example D/LoadFileFragment:     at com.yandex.disk.rest.RestClient.downloadFile(RestClient.java:325)
11-09 12:42:45.963 10998-12181/com.yandex.disk.rest.example D/LoadFileFragment:     at com.yandex.disk.rest.example.DownloadFileFragment$DownloadFileRetainedFragment$1.run(DownloadFileFragment.java:156)
11-09 12:42:45.963 10998-12181/com.yandex.disk.rest.example D/LoadFileFragment:     at java.lang.Thread.run(Thread.java:818)
11-09 12:42:45.968 10998-12181/com.yandex.disk.rest.example E/AndroidRuntime: FATAL EXCEPTION: Thread-3521
11-09 12:42:45.968 10998-12181/com.yandex.disk.rest.example E/AndroidRuntime: Process: com.yandex.disk.rest.example, PID: 10998
11-09 12:42:45.968 10998-12181/com.yandex.disk.rest.example E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.yandex.disk.rest.json.ApiError.getDescription()' on a null object reference
11-09 12:42:45.968 10998-12181/com.yandex.disk.rest.example E/AndroidRuntime:     at com.yandex.disk.rest.example.DownloadFileFragment$DownloadFileRetainedFragment$1.run(DownloadFileFragment.java:160)
11-09 12:42:45.968 10998-12181/com.yandex.disk.rest.example E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)

**Do you have any working examples?**

**Comment by javadev222** [comment]
Да, ошибка такая же.

**Comment by IlnazMan** [comment]
Ошибка, вероятно, связана с тем, что файл, в который вы сохраняете, не пустой.
