### ISSUE TITLE
Обновление зависимостей

### ISSUE THREAD

**Issue by agarkoff** [yandex-disk/yandex-disk-restapi-java#4]
Пожалуйста, обновите зависимости. Ваш пакет тянет okhttp второй версии до сих пор.

**Comment by PromanSEW** [comment]
Используйте мой форк
https://github.com/PromanSEW/yandex-disk-restapi-android
Импортируйте как модуль, и обновите зависимости на последние, всё будет работать как надо

**Comment by panovvitalik** [comment]
> Используйте мой форк https://github.com/PromanSEW/yandex-disk-restapi-android Импортируйте как модуль, и обновите зависимости на последние, всё будет работать как надо

Не работает. Добавил в проект: 
implementation 'com.yandex.android:disk-restapi-sdk:2.0'

Классы не видит.

**Comment by panovvitalik** [comment]
> Используйте мой форк https://github.com/PromanSEW/yandex-disk-restapi-android Импортируйте как модуль, и обновите зависимости на последние, всё будет работать как надо

Взял исходники напрямую - все работает. 
По-крайней мере функция downloadFile()
Спасибо!

**Comment by PromanSEW** [comment]
@panovvitalik Вы также можете использовать более актуальные форки моего репозитория:
https://github.com/PromanSEW/yandex-disk-restapi-android/network

**Comment by panovvitalik** [comment]
> @panovvitalik Вы также можете использовать более актуальные форки моего репозитория: https://github.com/PromanSEW/yandex-disk-restapi-android/network

Кто такие эти форки в депозиториях и как их брать я без понятия :-)
С исходниками и последними зависимостями, все вроде работает - и загрузка и выгрузка на яндекс диск. 
Спасибо еще раз

**Comment by panovvitalik** [comment]
> @panovvitalik Вы также можете использовать более актуальные форки моего репозитория: https://github.com/PromanSEW/yandex-disk-restapi-android/network

Работает с Android 7.1 по 13 
Но на Android  6 (SDK 23) после загрузки где-то 50 файлов - падает с ошибкой.
Не сильно критично, версия андроид уже мягко говоря не новая, но все-таки если что проблема есть ....

p.s.
может где-то какой-нибудь response.close() не делается внутри, или еще что ....

```
downloadFile error: socket failed: EMFILE (Too many open files)
        at libcore.io.IoBridge.socket(IoBridge.java:619)
        at java.net.PlainSocketImpl.create(PlainSocketImpl.java:198)
        at java.net.Socket.checkOpenAndCreate(Socket.java:689)
        at java.net.Socket.setSoTimeout(Socket.java:543)
        at com.android.org.conscrypt.OpenSSLSocketImpl.setSoTimeout(OpenSSLSocketImpl.java:1034)
        at com.android.org.conscrypt.OpenSSLSocketImplWrapper.setSoTimeout(OpenSSLSocketImplWrapper.java:111)
        at okhttp3.internal.connection.RealConnection.newCodec$okhttp(RealConnection.kt:615)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:82)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at <MY PACKAGE NAME>.disk_restapi_sdk.retrofit.RequestInterceptor.intercept(RequestInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at <MY PACKAGE NAME>.disk_restapi_sdk.RestClientIO.downloadUrl(RestClientIO.java:101)
        at <MY PACKAGE NAME>.disk_restapi_sdk.RestClient.downloadFile(RestClient.java:380)
        at <MY PACKAGE NAME>.sync.yandex.YandexDriveCloud$10.run(YandexDriveCloud.java:532)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by PromanSEW** [comment]
@panovvitalik ну здесь я уже не подскажу к сожалению. Я использовал только для редкой загрузки / отправки файлов, потом вообще выделил только используемый код, и сконвертил в Kotlin. Всё работает. Что здесь не учтено не имею понятия, и где искать тоже
